### ISSUE TITLE
import error in version 1.1.0

### ISSUE THREAD

**Issue by rathaustreppe** [LostInDarkMath/pedantic-python-decorators#15]
Hey there.

I upgraded the pedantic version to 1.1.0 but as soon I want to use it in my project, I get the error:

```python
Traceback (most recent call last):
  File "...\src\main.py", line 3, in <module>
    from src.converter.converter import Converter
  File "...\src\converter\converter.py", line 5, in <module>
    from pedantic import pedantic_class
  File "...\venv38\lib\site-packages\pedantic\__init__.py", line 1, in <module>
    from pedantic.class_decorators \
  File "...\venv38\lib\site-packages\pedantic\class_decorators.py", line 4, in <module>
    from pedantic.method_decorators import pedantic, pedantic_require_docstring, trace, timer
  File "...\venv38\lib\site-packages\pedantic\method_decorators.py", line 11, in <module>
    from pedantic.models.decorated_function import DecoratedFunction
ModuleNotFoundError: No module named 'pedantic.models'

```
Seems like sth breaks inside you package!
Hope you can fix it soon

**Comment by LostInDarkMath** [comment]
Looks like the file `decorated_function.py` is lost during deployment. I'll fix it.
