### ISSUE TITLE
type checking of two Subclasses a

### ISSUE THREAD

**Issue by rathaustreppe** [LostInDarkMath/pedantic-python-decorators#36]

**Comment by rathaustreppe** [comment]
Hey there, I found a bug:

I have two classes B and C that inherited from A. A has an equals method that I want to expect A and all of its subclasses.
But when executing the code below I get an error as soon as I call equals with objects of B and C.

```python
from typing import Type
from pedantic import pedantic_class

@pedantic_class
class A:
    def __init__(self, val: int) -> None:
        self.val = val

    def __eq__(self, other: 'A') -> bool: # other: A and all subclasses
        return self.val == other.val

@pedantic_class
class B(A):
    def __init__(self, val: int) -> None:
        super().__init__(val=val)

@pedantic_class
class C(A):
    def __init__(self, val: int) -> None:
        super().__init__(val=val)

if __name__ == '__main__':
    a = A(val=42)
    b = B(val=42)
    c = C(val=42)

    assert a == b # works
    assert a == c # works
    assert b == c # error
```

Error Message at line assert b == c:
```python
Traceback (most recent call last):
  File ".../src/schnellbug.py", line 31, in <module>
    assert b == c # error
  File "...venv38\lib\site-packages\pedantic\method_decorators.py", line 354, in wrapper
    return call.check_types()
  File "...\venv38\lib\site-packages\pedantic\models\function_call.py", line 62, in check_types
    self._check_type_param(params={k: v for k, v in d if not str(v).startswith('*')})
  File "...\venv38\lib\site-packages\pedantic\models\function_call.py", line 88, in _check_type_param
    _assert_value_matches_type(value=actual_value,
  File "...\venv38\lib\site-packages\pedantic\check_types.py", line 24, in _assert_value_matches_type
    raise PedanticTypeCheckException(msg)
pedantic.exceptions.PedanticTypeCheckException: In function A.__eq__:
Type hint is incorrect: Argument other=<__main__.C object at 0x000002AF1EC36640> of type <class '__main__.C'> does not match expected type A.
```

As I found out in https://stackoverflow.com/questions/46092104/subclass-in-type-hinting
it is actually:
```python
other:Type['A']
```
But then I get the error:
```python
Traceback (most recent call last):
  File "...\schnellbug.py", line 29, in <module>
    assert a == b # works
  File "...\venv38\lib\site-packages\pedantic\method_decorators.py", line 354, in wrapper
    return call.check_types()
  File "...\venv38\lib\site-packages\pedantic\models\function_call.py", line 62, in check_types
    self._check_type_param(params={k: v for k, v in d if not str(v).startswith('*')})
  File "...\venv38\lib\site-packages\pedantic\models\function_call.py", line 88, in _check_type_param
    _assert_value_matches_type(value=actual_value,
  File "...\venv38\lib\site-packages\pedantic\check_types.py", line 24, in _assert_value_matches_type
    raise PedanticTypeCheckException(msg)
pedantic.exceptions.PedanticTypeCheckException: In function A.__eq__:
Type hint is incorrect: Argument other=<__main__.A object at 0x0000028B0A766B80> of type <class '__main__.A'> does not match expected type typing.Type[ForwardRef('A')].
```
So it fails at a == b.
What is wrong? Is it a bug?
I use Python 3.8 and the bug occured in (at least) pedantic 1.2.4 and 1.2.7.
