### ISSUE TITLE
Disable pedantic doesn't works as expected

### ISSUE THREAD

**Issue by LostInDarkMath** [LostInDarkMath/pedantic-python-decorators#37]
Error message:
```
Traceback (most recent call last):
  File "C:/Users/WILLI/AppData/Roaming/JetBrains/PyCharm2020.3/scratches/bug.py", line 21, in <module>
    f.do()
  File "C:/Users/WILLI/AppData/Roaming/JetBrains/PyCharm2020.3/scratches/bug.py", line 12, in do
    print(self.bar(value=self._value))
TypeError: bar() got multiple values for argument 'value'
```

Example for reproducing the bug:
```python
from pedantic import pedantic_class, disable_pedantic

disable_pedantic()


@pedantic_class
class Foo:
    def __init__(self) -> None:
        self._value = 42

    def do(self) -> None:
        print(self.bar(value=self._value))

    @staticmethod
    def bar(value: int) -> int:
        return value + 75


if __name__ == '__main__':
    f = Foo()
    f.do()

```

**Comment by LostInDarkMath** [comment]
A solution for this could be by adding the check on the class decorator level:
```
def for_all_methods(decorator: F) -> Callable[[C], C]:
    """
    Example:
    >>> @for_all_methods(pedantic)
    ... class MyClass(object):
    ...     def m1(self): pass
    ...     def m2(self, x): pass
    """
    def decorate(cls: C) -> C:
        if not is_enabled():
            return cls
```

**Comment by LostInDarkMath** [comment]
There is a another bug, which is related to this: 
```python
from pedantic import timer_class

@timer_class
class Foo:
    def __init__(self) -> None:
        self._value = 42

    def do(self) -> None:
        print(self.bar(value=self._value))

    @staticmethod
    def bar(value: int) -> int:
        return value + 75


if __name__ == '__main__':
    f = Foo()
    f.do()
```
