### ISSUE TITLE
pedantic fails at Optional TypeHints

### ISSUE THREAD

**Issue by rathaustreppe** [LostInDarkMath/pedantic-python-decorators#5]
Hey there,
the pedantic decorator seems to fail with optional arguments.
When executing the snippet below...

```python
class MyClass():
    @pedantic
    def foo(self, a:int, b: Optional[int] = 1) -> int:
        return a+b

if __name__ == '__main__':
    myclass = MyClass()
    print(myclass.foo(a=10)) # should print 11
```
... pedantic prints:

```python
Traceback (most recent call last):
  File ".../src/mypy.py", line 13, in <module>
    print(myclass.foo(a=10)) # should print 11
  File "...\lib\site-packages\pedantic\method_decorators.py", line 355, in wrapper
    return __require_kwargs_and_type_checking(func=func, args=args, kwargs=kwargs, annotations=annotations)
  File "...\lib\site-packages\pedantic\method_decorators.py", line 52, in __require_kwargs_and_type_checking
    assert len(kwargs) + 1 == len(annotations), \
AssertionError: Function "foo" misses some type hints or arguments: {'a': 10}, {'return': <class 'int'>, 'a': <class 'int'>, 'b': typing.Union[int, NoneType]}
```

**Comment by LostInDarkMath** [comment]
Thx for the report! It should be fixed by https://github.com/LostInDarkMath/pedantic-python-decorators/pull/7/commits/b5245414c463f9b549e420437cf21563cc2c6fd0 which will be included in the next release.
