### ISSUE TITLE
validate_args accesses custom class instead of arguments when decorated with pedantic

### ISSUE THREAD

**Issue by rathaustreppe** [LostInDarkMath/pedantic-python-decorators#6]
Heyho,

i came across a problem when decorating a function with validate_args and pedantic.
Instead of checking my function argument, validate_args accesses the instance of the class thus failing.

Example:
I want to check if the int ist greater then 0. I decorate this function with pedantic and call it:

```python
from pedantic import validate_args, pedantic
class classA:
    def __init__(self, a: int) -> None:
        self.a = a

    @validate_args(lambda x: (x > 0,f'Argument should be greater then 0, but it was {x}.'))
    @pedantic
    def some_calculation(self, x: int) -> int:
        return x

if __name__ == '__main__':
    classA = classA(a=10)
    classA.some_calculation(x=15)
```
But I get the error:
```python
Traceback (most recent call last):
  File ".../src/pypypy.py", line 17, in <module>
    classA.some_calculation(x=15)
  File "...\lib\site-packages\pedantic\method_decorators.py", line 289, in wrapper
    res, msg = validator(arg)
  File ".../src/pypypy.py", line 9, in <lambda>
    @validate_args(lambda x: (x > 0,f'Argument should be greater then 0, but it was {x}.'))
TypeError: '>' not supported between instances of 'classA' and 'int'
```
It seems like, validate_args wants to compare classA-object with an int which of course does not work.
If I switch the decorators, pedantic says:
```python
File "...\lib\site-packages\pedantic\method_decorators.py", line 25, in __require_kwargs
    assert args_without_self == (), f'Use kwargs when you call {func.__name__}! {args_without_self}'
AssertionError: Use kwargs when you call some_calculation! (<__main__.classA object at 0x000001991322D8E0>,)
```
Hope you can enable double decorators like this! Would be really helpful! (:

**Comment by LostInDarkMath** [comment]
Fixed in https://github.com/LostInDarkMath/pedantic-python-decorators/pull/7/commits/09064ae9122ec623fe055e3c733b9ae748b4e6f9.
